### PR TITLE
blackmagic_flash.sh updated to support osx

### PR DESCRIPTION
**Pull request by pavel-kirienko**
Hey @davidbuzz, could you please test this on OSX.

### CODE REVIEW

**Comment by pavel-kirienko** [comment]
@davidbuzz fixed!

**Comment by pavel-kirienko** [comment]
@davidbuzz should be good to go now.

**Comment by pavel-kirienko** [comment]
@davidbuzz can we merge this now?

**Comment by davidbuzz** [comment]
yep, works for me.

**Pull request merged**
